// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8TULyRbDCdWvpmo7UjtYYRP0nVNN1gk',
    appId: '1:611732866028:web:83d2664c8264153980f6c9',
    messagingSenderId: '611732866028',
    projectId: 'full-e-commerce-8b6ed',
    authDomain: 'full-e-commerce-8b6ed.firebaseapp.com',
    storageBucket: 'full-e-commerce-8b6ed.firebasestorage.app',
    measurementId: 'G-96676B49DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQWVprR5dDtrZZLENf_hXBC2aTelOp2o',
    appId: '1:611732866028:android:0dbf44b1cbe2cddd80f6c9',
    messagingSenderId: '611732866028',
    projectId: 'full-e-commerce-8b6ed',
    storageBucket: 'full-e-commerce-8b6ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXzgTGrfBVKOacYaAspLLU7Rmn_BbGMc',
    appId: '1:611732866028:ios:73ebdf9800729f7480f6c9',
    messagingSenderId: '611732866028',
    projectId: 'full-e-commerce-8b6ed',
    storageBucket: 'full-e-commerce-8b6ed.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFullapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJXzgTGrfBVKOacYaAspLLU7Rmn_BbGMc',
    appId: '1:611732866028:ios:73ebdf9800729f7480f6c9',
    messagingSenderId: '611732866028',
    projectId: 'full-e-commerce-8b6ed',
    storageBucket: 'full-e-commerce-8b6ed.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFullapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8TULyRbDCdWvpmo7UjtYYRP0nVNN1gk',
    appId: '1:611732866028:web:66a5b88c19e3a1b980f6c9',
    messagingSenderId: '611732866028',
    projectId: 'full-e-commerce-8b6ed',
    authDomain: 'full-e-commerce-8b6ed.firebaseapp.com',
    storageBucket: 'full-e-commerce-8b6ed.firebasestorage.app',
    measurementId: 'G-HNEKCEKR1L',
  );
}
